apiVersion: apps/v1
kind: Deployment
metadata:
  name: asterisk
  namespace: asterisk
spec:
  replicas: 3
  selector:
    matchLabels:
      app: asterisk
  template:
    metadata:
      labels:
        app: asterisk
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: app
                      operator: In
                      values:
                        - asterisk
                topologyKey: "kubernetes.io/hostname"
      containers:
        - name: asterisk
          image: asterisk/asterisk:latest
          command: ["/bin/sh", "-c"]
          args:
            - |
              mkdir -p /var/run/asterisk && \
              chown -R asterisk:asterisk /var/run/asterisk && \
              exec /usr/sbin/asterisk -f -vvv
          securityContext:
            runAsUser: 0
            runAsGroup: 0
            allowPrivilegeEscalation: true
          ports:
            - containerPort: 5060
              protocol: UDP
            - containerPort: 5060
              protocol: TCP
            - containerPort: 10000
              protocol: UDP
            - containerPort: 20000
              protocol: UDP
          volumeMounts:
            - name: config
              mountPath: /etc/asterisk
      volumes:
        - name: config
          configMap:
            name: asterisk-config
