apiVersion: apps/v1
kind: Deployment
metadata:
  name: asterisk
  namespace: asterisk
spec:
  replicas: 3
  selector:
    matchLabels:
      app: asterisk
  template:
    metadata:
      labels:
        app: asterisk
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: app
                      operator: In
                      values:
                        - asterisk
                topologyKey: "kubernetes.io/hostname"
      containers:
        - name: asterisk
          image: asterisk/asterisk:20.5.1   # ✅ Full-featured image with PJSIP
          ports:
            - containerPort: 5060
              protocol: UDP
            - containerPort: 5060
              protocol: TCP
            - containerPort: 10000
              protocol: UDP
            - containerPort: 20000
              protocol: UDP
          volumeMounts:
            - name: config
              mountPath: /srv/etc/asterisk
      volumes:
        - name: config
          configMap:
            name: asterisk-config
